QUERIES = [
    "machine learning",
    "artificial intelligence",
    "climate change",
    "renewable energy",
    "genomics",
    "CRISPR",
    "quantum computing",
    "robotics",
    "internet of things",
    "blockchain",
    "natural language processing",
    "computer vision",
    "cybersecurity",
    "human-computer interaction",
    "biomedical engineering",
    "neuroscience",
    "materials science",
    "nanotechnology",
    "agriculture technology",
    "autonomous vehicles",
    "edge computing",
    "smart cities",
    "5G networks",
    "digital twins",
    "data privacy",
    "carbon capture",
    "fusion energy",
    "e-waste management",
    "sustainable development",
    "bioinformatics",
    "ecosystem restoration",
    "renewable hydrogen",
    "space exploration",
    "satellite data analysis",
    "mental health technologies",
    "disease modeling",
    "covid-19 vaccine",
    "epigenetics",
    "artificial general intelligence",
    "solar energy forecasting",
    "digital pathology",
    "quantum cryptography",
    "explainable AI",
    "precision agriculture",
    "computational fluid dynamics",
    "digital phenotyping",
    "neuroprosthetics",
    "climate resilient crops",
    "bioinspired robotics",
    "computational neuroscience",
    "digital therapeutics",
    "computational chemistry",
    "synthetic biology",
    "ocean acidification",
    "wearable biosensors",
    "environmental DNA",
    "federated learning",
    "molecular diagnostics",
    "human microbiome",
    "plastic degradation",
    "cyber-physical systems",
    "ecoacoustics",
    "quantum sensors",
    "computational linguistics",
    "geomatics",
    "urban heat islands",
    "space weather modeling",
    "digital biomarkers",
    "smart manufacturing",
    "metaverse technologies",
    "livestock genomics",
    "AI in healthcare",
    "bioelectronic medicine",
    "AI for education",
    "digital agriculture",
    "energy harvesting materials",
    "self-healing materials",
    "AI-driven drug discovery",
    "extreme weather prediction",
    "quantum machine learning"
]